### ISSUE TITLE
[4.0.1]: ES modules is not supported.

### ISSUE THREAD

**Issue by kalicki** [gabrielizaias/cnpj#22] opened 2021-10-16 00:01 UTC
Version 4.0.1 ready?

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/cnpj/dist/index.js
require() of ES modules is not supported.
require() of /node_modules/cnpj/dist/index.js from /.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/cnpj/package.json.
```

**Comment by gabeins** [comment] 2021-10-18 11:56
Hi @kalicki,

From the error message it seems that you are trying to consume the package via `const cnpj = require('cnpj')` instead of `import * as cnpj from 'cnpj'`. Is that the case?

From version `4.x` forward, this package only exports an ES Module and must be used with `import` syntax instead of `require`. See https://nodejs.org/api/esm.html#esm_enabling

If you are unable to make your own code use the ES Module syntax, it's recommended that you keep using `v3.2.1` until you can update to the newer format. The API is the same.

Thank you for using the package and feel free to ask any further questions.

**Comment by kalicki** [comment] 2021-10-18 12:58
Hey @gabrielizaias 

In fact I've always used `import * as CNPJ from 'cnpj';` like this even in 3.2.1
I just updated the package and it doesn't work anymore =/

Thanks

---
Update: I think the problem is in nextjs with esm

**Comment by gabeins** [comment] 2021-10-19 09:19
@kalicki they have announced experimental support for it on 11.1, maybe that works for you? https://nextjs.org/blog/next-11-1#es-modules-support

**Comment by samueldemoura** [comment] 2021-11-12 15:42
Just leaving a comment to possibly save someone else some troubleshooting time: v3.2.1 also does _not_ work for some reason, but downgrading further down to v3.2.0 gets everything back to normal again. At least that was my experience when using the package inside a NestJS project.

**Comment by gabeins** [comment] 2021-11-12 15:49
@samueldemoura I'm keen on investigating this, could you help me out and provide a minimal reproduction?

**Comment by samueldemoura** [comment] 2021-11-12 15:54
It's not really a bug as far as I understand it - In my case it was caused by NestJS not supporting ES modules, so the TypeScript code gets transpiled down to CommonJS where:
```typescript
import { validate } from 'cnpj';
```
Gets converted into:
```javascript
const cnpj_1 = require("cnpj");
```
Triggering the error seen in the opening message. If you're still interested, I can try whipping together a minimal reproduction repo though.

**Comment by gabeins** [comment] 2021-11-15 20:26
> […] it was caused by NestJS not supporting ES modules […]

I see. If that's the case then we can close this one. Thanks for the follow up.

@samueldemoura you mentioned it didn't work for you with `v3.2.1`, that version was just a dependency bump from `v3.2.0` and it was still CJS so I wonder what could be going on there as well… If you feel like it warrants a deeper look I'm down to spend a couple hours with a minimal reproduction.

**Closed as completed by gabeins** 2021-11-15 20:26 UTC
